### PR TITLE
fix bug in updating pluginmeta details

### LINKED ISSUE #45: Fix updating plugin to enable partial update
@jbernal0019 trying to update pluginmeta detail has a bug and does not function, the query dict instance is not mutable

### PR DESCRIPTION
**Pull request by EUGINELETHAL**
fix #45 Fix error in updating pluginmeta details

### CODE REVIEW

**Comment by jennydaman** [comment]
Unexpected tests fail, I am retrying them.

Anyways, we should probably use `example.com` to stay out of the legal grey area....

**Comment by jennydaman** [comment]
The tests were broken in the first place, false negative (i.e. not your fault @EUGINELETHAL)

The 400 response is

```json
{'collection': {'version': '1.0', 'href': 'http://testserver/api/v1/178/', 'error': {'message': '{"name": ["This field is required."]}'}}}
```

**Comment by jennydaman** [comment]
@EUGINELETHAL do you want to take a look, or have one of us fix it?

**Comment by jbernal0019** [comment]
Hey @EUGINELETHAL  Collection+JSON only supports GET, POST, PUT and DELETE http://www.amundsen.com/media-types/collection/

The popped parameters should be implemented as read-only

**Comment by EUGINELETHAL** [comment]
Thanks for feedback let me work on it

**Pull request closed without merging**
